### ISSUE TITLE
Carcass doesn't count towards kills in rude custom levels

### ISSUE THREAD

**Issue by FNAF-fan-9000** [Hydraxous/Carcass#1]
As the title states, Carcass doesn't count towards kills, this is the case even with the "Dont Count As Kills" checkbox if unchecked and I don't really know if I can do anything on my end

**Comment by Hydraxous** [comment]
Should be fixed in [1.0.3](https://github.com/Hydraxous/Carcass/releases/tag/1.0.3)

If you are using Rude, you can delete the folder Assets/Carcass and the file Assets/RudeScripts/CarcassEnemy.dll and import the [newer package version](https://github.com/Hydraxous/Carcass/releases/download/1.0.3/CarcassCustomEnemy_Rude.unitypackage).
